import { Container, SelectList, Text, type SelectItem } from "@earendil-works/pi-tui";
import { type ExtensionAPI, type ExtensionContext } from "@selesai/code";
import { classify, priorHumanContext } from "./classifier.ts";
import { TIERS, configPaths, loadConfig, updateConfig, type AutoModelConfig, type Tier } from "./config.ts";

const STATUS_KEY = "auto-model";
type Model = { provider: string; id: string };
function identity(model: Model | undefined): string | undefined { return model ? `${model.provider}/${model.id}` : undefined; }
function models(ctx: ExtensionContext): Model[] { return (ctx.scopedModels.length ? ctx.scopedModels.map(({ model }) => model) : ctx.modelRegistry.getAvailable()) as Model[]; }
function findModel(ctx: ExtensionContext, ref: string | undefined): Model | undefined { const [provider, ...rest] = ref?.split("/") ?? []; const id = rest.join("/"); if (!provider || !id || !models(ctx).some((m) => m.provider === provider && m.id === id)) return undefined; return ctx.modelRegistry.find(provider, id) as Model | undefined; }
function notify(ctx: ExtensionContext, text: string) { try { ctx.ui.notify?.(text, "warning"); } catch { /* UI notification failures must not block the prompt. */ } }
function show(ctx: ExtensionContext, config: AutoModelConfig, suspended: boolean, last?: string) { const mappings = TIERS.map((t) => `${t}: ${config.tiers[t] ?? "unset"}`).join("\n"); ctx.ui.notify(`Auto model ${config.enabled ? "enabled" : "disabled"}${suspended ? " (manual selection suspended)" : ""}\nclassifier: ${config.classifier.type}${config.classifier.model ? ` (${config.classifier.model})` : ""}\n${mappings}${last ? `\nlast: ${last}` : ""}`, "info"); }
async function picker(ctx: any, config: AutoModelConfig): Promise<{ tier: Tier; model: string } | undefined> { const choices: SelectItem[] = TIERS.map((tier) => ({ value: tier, label: tier, description: config.tiers[tier] ?? "unset" })); const tier = await ctx.ui.custom((tui: any, theme: any, _kb: unknown, done: (v: Tier | undefined) => void) => { const root = new Container(); root.addChild(new Text(theme.fg("accent", "Auto model: choose tier"), 1, 0)); const list = new SelectList(choices, 4, { selectedPrefix: (v: string) => theme.fg("accent", v), selectedText: (v: string) => theme.fg("accent", v) } as any); list.onSelect = (item: SelectItem) => done(item.value as Tier); list.onCancel = () => done(undefined); root.addChild(list); return root; }); if (!tier) return undefined; const available = models(ctx).map((m) => ({ value: identity(m)!, label: identity(m)!, description: m.provider })); const model = await ctx.ui.custom((tui: any, theme: any, _kb: unknown, done: (v: string | undefined) => void) => { const root = new Container(); root.addChild(new Text(theme.fg("accent", `Auto model: ${tier}`), 1, 0)); const list = new SelectList(available, Math.min(available.length, 10), { selectedPrefix: (v: string) => theme.fg("accent", v), selectedText: (v: string) => theme.fg("accent", v) } as any); list.onSelect = (item: SelectItem) => done(item.value as string); list.onCancel = () => done(undefined); root.addChild(list); return root; }); return model ? { tier, model } : undefined; }

export default function autoModel(pi: ExtensionAPI): void {
 let config: AutoModelConfig; let suspended = false; let automaticSwitch = false; let last: string | undefined; let routing = Promise.resolve();
 const reload = async (ctx: ExtensionContext) => config = await loadConfig(ctx.cwd, ctx.isProjectTrusted());
 pi.on("session_start", async (_event, ctx) => { try { await reload(ctx); const branch: any[] = await ctx.sessionManager.getBranch(); const decision = [...branch].reverse().find((e) => e.type === "custom" && e.customType === "auto-model-decision"); const suspension = [...branch].reverse().find((e) => e.type === "custom" && e.customType === "auto-model-suspension"); suspended = suspension?.data?.suspended === true; if (decision?.data?.tier && decision.data.target) { last = `${decision.data.tier} -> ${decision.data.target}`; ctx.ui.setStatus(STATUS_KEY, `auto:${last}`); } else if (suspended) ctx.ui.setStatus(STATUS_KEY, "auto: suspended"); } catch { notify(ctx, "Auto model: failed to restore routing state; continuing with defaults."); } });
 pi.on("model_select", (event, ctx) => { if (automaticSwitch || event.source === "restore") return; suspended = true; pi.appendEntry("auto-model-suspension", { suspended: true, cause: "manual-model-select", timestamp: new Date().toISOString() }); ctx.ui.setStatus(STATUS_KEY, "auto: suspended"); });
 pi.on("input", async (event, ctx) => { if (event.source === "extension" || event.streamingBehavior !== undefined || !ctx.isIdle() || suspended) return { action: "continue" }; routing = routing.catch(() => undefined).then(async () => { try { await reload(ctx); if (!config.enabled || !ctx.isIdle() || suspended) return; const branch: any[] = await ctx.sessionManager.getBranch(); const result = await classify(ctx, config, event.text, priorHumanContext(branch, config)); if (!ctx.isIdle() || suspended) return; const target = findModel(ctx, config.tiers[result.tier]); if (!target) { notify(ctx, `Auto model: ${result.tier} target is unavailable or out of scope; keeping current model.`); return; } if (identity(target) === identity(ctx.model as Model | undefined)) return; automaticSwitch = true; try { const switched = await pi.setModel(target as any); if (switched === false) { notify(ctx, "Auto model: could not select target; keeping current model."); return; } last = `${result.tier} -> ${identity(target)}`; pi.appendEntry("auto-model-decision", { tier: result.tier, target: identity(target), cause: result.cause, timestamp: new Date().toISOString() }); ctx.ui.setStatus(STATUS_KEY, `auto:${last}`); } catch { notify(ctx, "Auto model: could not select target; keeping current model."); } finally { automaticSwitch = false; } } catch { notify(ctx, "Auto model: routing failed; keeping current model."); } }); await routing.catch(() => undefined); return { action: "continue" }; });
 pi.registerCommand("auto-model-settings", { description: "Configure automatic model routing", handler: async (args, ctx) => { await reload(ctx); const tokens = args.trim().split(/\s+/).filter(Boolean); const project = tokens.includes("--project"); const [command, tier, ...tail] = tokens.filter((value) => value !== "--project"); const scope = project && ctx.isProjectTrusted() ? "project" : "global"; const cleanTail = tail; const paths = configPaths(ctx.cwd); const save = async (scope: "global" | "project", override: any) => updateConfig(paths[scope], override); if (!command) { if (ctx.mode !== "tui") { show(ctx, config, suspended, last); return; } const choice = await picker(ctx, config); if (choice) { config.tiers[choice.tier] = choice.model; await save(scope, { tiers: { [choice.tier]: choice.model } }); show(ctx, config, suspended, last); } return; } if (command === "show") return show(ctx, config, suspended, last); if (command === "enable") { config.enabled = true; suspended = false; pi.appendEntry("auto-model-suspension", { suspended: false, cause: "manual-enable", timestamp: new Date().toISOString() }); await save(scope, { enabled: true }); return show(ctx, config, false, last); } if (command === "disable") { config.enabled = false; await save(scope, { enabled: false }); return show(ctx, config, suspended, last); } if (command === "classifier" && (tier === "llm" || tier === "heuristic")) { config.classifier.type = tier; if (cleanTail[0]) config.classifier.model = cleanTail.join(" "); await save(scope, { classifier: { type: tier, ...(cleanTail[0] ? { model: cleanTail.join(" ") } : {}) } }); return show(ctx, config, suspended, last); } if (command === "set" && (TIERS as readonly string[]).includes(tier) && cleanTail[0]) { const target = cleanTail.join(" "); if (!findModel(ctx, target)) return notify(ctx, "Auto model: choose an available scoped provider/modelId."); config.tiers[tier as Tier] = target; await save(scope, { tiers: { [tier as Tier]: target } }); return show(ctx, config, suspended, last); } if (command === "test" && cleanTail.length + (tier ? 1 : 0) > 0) { const prompt = [tier, ...cleanTail].filter(Boolean).join(" "); const result = await classify(ctx, config, prompt); return ctx.ui.notify(`Auto model test: ${result.tier} -> ${config.tiers[result.tier] ?? "unset"} (${result.cause})`, "info"); } notify(ctx, "Usage: /auto-model-settings [show|enable|disable|set <tier> <provider/model>|classifier <llm|heuristic> [provider/model]|test <prompt>]"); } });
}
