import { describe, expect, it, vi } from "vitest";
vi.mock("@selesai/code", () => ({ CONFIG_DIR_NAME: ".selesai", getAgentDir: () => "/agent" }));
vi.mock("@earendil-works/pi-tui", () => ({ Container: class {}, SelectList: class {}, Text: class {} }));
const { classifyMock, loadConfigMock, updateConfigMock } = vi.hoisted(() => ({ classifyMock: vi.fn(async () => ({ tier: "medium", cause: "fallback" })), loadConfigMock: vi.fn(async () => ({ enabled: true, classifier: { type: "heuristic", timeoutMs: 3000, contextTurns: 3, contextCharsPerTurn: 300 }, tiers: { simple: undefined, medium: "p/medium", complex: undefined, reasoning: undefined }, fallback: "current", manualSelection: "suspend-until-enabled" })), updateConfigMock: vi.fn(async () => {}) }));
vi.mock("./classifier.ts", () => ({ classify: classifyMock, priorHumanContext: vi.fn(() => "") }));
vi.mock("./config.ts", async () => ({ ...(await vi.importActual<typeof import("./config.ts")>("./config.ts")), loadConfig: loadConfigMock, updateConfig: updateConfigMock }));
import extension from "./index.ts";

function setup(trusted = false) { const handlers = new Map<string, Function>(); const commands = new Map<string, Function>(); const setModel = vi.fn(async () => true); const pi: any = { on: (n: string, h: Function) => handlers.set(n, h), registerCommand: (n: string, options: any) => commands.set(n, options.handler), setModel, appendEntry: vi.fn() };  const model = { provider: "p", id: "current" }; const ctx: any = { cwd: "/work", isProjectTrusted: () => trusted, isIdle: () => true, scopedModels: [], model, modelRegistry: { getAvailable: () => [model, { provider: "p", id: "medium" }], find: (p: string, id: string) => ({ provider: p, id }) }, sessionManager: { getBranch: async () => [] }, ui: { notify: vi.fn(), setStatus: vi.fn() }, mode: "print" }; extension(pi); return { handlers, commands, pi, ctx }; }
describe("auto-model lifecycle routing", () => {
 it("rechecks suspension after queued classification before switching", async () => { const { handlers, pi, ctx } = setup(); let release!: () => void; classifyMock.mockImplementationOnce(() => new Promise((resolve) => { release = () => resolve({ tier: "medium", cause: "fallback" }); })); const queued = handlers.get("input")!({ text: "fix it", source: "interactive" }, ctx); await vi.waitFor(() => expect(release).toBeTypeOf("function")); await handlers.get("model_select")!({ source: "set" }, ctx); release(); await queued; expect(pi.setModel).not.toHaveBeenCalled(); });
 it("routes enabled input through a successful model switch and records it", async () => { const { handlers, pi, ctx } = setup(); await handlers.get("input")({ text: "fix it", source: "interactive" }, ctx); expect(pi.setModel).toHaveBeenCalledWith({ provider: "p", id: "medium" }); expect(pi.appendEntry).toHaveBeenCalledWith("auto-model-decision", expect.objectContaining({ tier: "medium", target: "p/medium" })); });
 it("continues after a rejected routing task and routes a later eligible input", async () => { const { handlers, pi, ctx } = setup(); loadConfigMock.mockRejectedValueOnce(new Error("unreadable config")); expect(await handlers.get("input")({ text: "first", source: "interactive" }, ctx)).toEqual({ action: "continue" }); expect(await handlers.get("input")({ text: "fix it", source: "interactive" }, ctx)).toEqual({ action: "continue" }); expect(pi.setModel).toHaveBeenCalledWith({ provider: "p", id: "medium" }); });
 it("restores manual suspension and does not route until enabled", async () => { const { handlers, pi, ctx } = setup(); ctx.sessionManager.getBranch = async () => [{ type: "custom", customType: "auto-model-suspension", data: { suspended: true } }]; await handlers.get("session_start")({}, ctx); await handlers.get("input")({ text: "fix it", source: "interactive" }, ctx); expect(pi.setModel).not.toHaveBeenCalled(); await handlers.get("model_select")({ source: "restore" }, ctx); expect(pi.appendEntry).not.toHaveBeenCalledWith("auto-model-suspension", expect.anything()); });
});
describe("auto-model command scopes", () => {
 it.each(["enable --project", "disable --project"])("uses trusted project scope for %s", async (args) => { const { commands, ctx } = setup(true); await commands.get("auto-model-settings")!(args, ctx); expect(updateConfigMock).toHaveBeenCalledWith("/work/.selesai/extensions/auto-model/config.json", expect.any(Object)); updateConfigMock.mockClear(); });
});
describe("auto-model lifecycle exclusions", () => {
 it("skips extension and queued streaming inputs", async () => { const { handlers, pi, ctx } = setup(); await handlers.get("input")({ text: "fix it", source: "extension" }, ctx); await handlers.get("input")({ text: "fix it", source: "interactive", streamingBehavior: "steer" }, ctx); expect(pi.setModel).not.toHaveBeenCalled(); });
 it("manual selection suspends auto routing", async () => { const { handlers, pi, ctx } = setup(); await handlers.get("model_select")({ source: "set" }, ctx); await handlers.get("input")({ text: "fix it", source: "interactive" }, ctx); expect(pi.setModel).not.toHaveBeenCalled(); });
 it("ignores restored model selections", async () => { const { handlers, pi, ctx } = setup(); await handlers.get("model_select")({ source: "restore" }, ctx); expect(pi.appendEntry).not.toHaveBeenCalledWith("auto-model-suspension", expect.anything()); });
 it("does not record failed model switches", async () => { const { handlers, pi, ctx } = setup(); pi.setModel.mockResolvedValue(false); await handlers.get("input")({ text: "fix it", source: "interactive" }, ctx); expect(pi.appendEntry).not.toHaveBeenCalledWith("auto-model-decision", expect.anything()); });
});
